// ——— content data ———————————————————————————————————————————
const SITE = {
  name: "Yim Hyangja",
  nameKo: "임향자",
  hanja: "林香子",
  tagline: "Fine Art & Conceptual Photography",
  location: "Seoul, KR",
  years: "Practice since 2011",
  studio: "Studio Hyangja",
  email: "studio@hyangja.kr",
  phone: "+82 2 000 0000",
  address: ["Seongsu-dong 2-ga", "Seongdong-gu, Seoul"],
  social: [
    { label: "Instagram", href: "#", handle: "@yim.hyangja" },
    { label: "Are.na", href: "#", handle: "yim-hyangja" },
    { label: "Journal", href: "#", handle: "Substack" },
  ],
};

const SERIES = [
  {
    id: "quiet-rooms",
    num: "No. 01",
    title: "Quiet Rooms",
    titleKo: "고요한 방들",
    year: "2024",
    count: 9,
    medium: "Medium format film",
    dims: "120 × 150 cm",
    edition: "Edition of 7 + 2 AP",
    tags: ["Interior", "Still life", "Film"],
    lede: "비어 있음의 밀도를 측정하려는 시도. 사람이 떠난 뒤 방에 남는 공기의 두께를 기록한 연작.",
    essay: [
      "어느 해 겨울, 할머니의 집을 정리하며 처음으로 빈 방을 오래 바라보았다. 아무도 없는데도 방은 여전히 누군가의 무게를 품고 있었다. 벽지의 변색, 문틀에 남은 지문, 햇빛이 닿아 더 바랜 마룻바닥.",
      "이 연작은 그 두께를 측정하려는 시도다. 사물을 찍는 것이 아니라, 사물이 있었다는 사실이 공간에 남긴 흔적을 찍는다. 카메라는 증거가 아니라 조문객이 된다.",
      "촬영은 모두 자연광으로 이루어졌으며, 노출은 필름 한 롤당 평균 14초. 오래 들여다본 것들만 오래 남는다.",
    ],
    plates: [
      { kind: "full",  ratio: "ar-4x5",  caption: "Plate I — Room with closed curtain",   no: "01/09" },
      { kind: "pair",  a: { ratio: "ar-4x5", no: "02/09" }, b: { ratio: "ar-4x5", no: "03/09" } },
      { kind: "wide",  ratio: "ar-21x9", caption: "Plate IV — Hallway, late afternoon",   no: "04/09" },
      { kind: "left",  ratio: "ar-4x3",  caption: "Plate V — A table set for nobody",     no: "05/09" },
      { kind: "right", ratio: "ar-4x5",  caption: "Plate VI — Bedroom, inherited",        no: "06/09" },
      { kind: "pair",  a: { ratio: "ar-4x3", no: "07/09" }, b: { ratio: "ar-4x5", no: "08/09" } },
      { kind: "full",  ratio: "ar-4x5",  caption: "Plate IX — Window at dusk",            no: "09/09" },
    ],
  },
  {
    id: "salt-and-paper",
    num: "No. 02",
    title: "Salt and Paper",
    titleKo: "소금과 종이",
    year: "2023",
    count: 9,
    medium: "Archival pigment print",
    dims: "80 × 100 cm",
    edition: "Edition of 5 + 1 AP",
    tags: ["Still life", "Studio", "Material"],
    lede: "만질 수 없는 것들을 만질 수 있는 것으로 옮기기. 물질의 목소리를 빌려 감정을 발음하는 연구.",
    essay: [
      "소금은 운다고 한다. 소금 장인들은 결정이 자라는 소리를 '운다'고 표현한다. 이 연작은 그 울음을 시각으로 옮기려는 반복된 실패의 기록이다.",
      "스튜디오에서 13개월에 걸쳐 진행되었고, 종이와 소금, 물, 빛만을 도구로 삼았다. 재료는 흔하지만 관계는 희박하다.",
    ],
    plates: [
      { kind: "wide",  ratio: "ar-21x9", caption: "Plate I — Salt forming on cotton",     no: "01/09" },
      { kind: "pair",  a: { ratio: "ar-4x5", no: "02/09" }, b: { ratio: "ar-4x5", no: "03/09" } },
      { kind: "full",  ratio: "ar-4x5",  caption: "Plate IV — Paper, folded seven times", no: "04/09" },
      { kind: "left",  ratio: "ar-4x3",  caption: "Plate V — Evaporation, day 47",        no: "05/09" },
      { kind: "pair",  a: { ratio: "ar-4x3", no: "06/09" }, b: { ratio: "ar-4x5", no: "07/09" } },
      { kind: "right", ratio: "ar-4x5",  caption: "Plate VIII — Crystal formation",       no: "08/09" },
      { kind: "full",  ratio: "ar-4x3",  caption: "Plate IX — Salt plain, studio",        no: "09/09" },
    ],
  },
  {
    id: "mother-tongue",
    num: "No. 03",
    title: "Mother Tongue",
    titleKo: "모어(母語)",
    year: "2022",
    count: 9,
    medium: "Silver gelatin print",
    dims: "Variable",
    edition: "Unique prints",
    tags: ["Portrait", "Family", "Black & white"],
    lede: "네 세대의 여성들이 서로를 마주 본다. 언어가 닳아 없어지기 전에 남기는 흑백의 족보.",
    essay: [
      "이 연작은 내 증조모, 조모, 어머니, 그리고 나를 순서대로 찍은 것이 아니다. 우리는 나란히 앉았고, 서로를 찍었다. 누가 누구를 보는지가 아니라, 무엇이 서로를 보게 만드는지를 묻는 작업.",
    ],
    plates: [
      { kind: "full",  ratio: "ar-4x5",  caption: "Plate I — My grandmother, photographed by my mother", no: "01/09" },
      { kind: "pair",  a: { ratio: "ar-4x5", no: "02/09" }, b: { ratio: "ar-4x5", no: "03/09" } },
      { kind: "wide",  ratio: "ar-16x9", caption: "Plate IV — Four hands, one table",     no: "04/09" },
      { kind: "left",  ratio: "ar-4x5",  caption: "Plate V — Mother, waiting",            no: "05/09" },
      { kind: "pair",  a: { ratio: "ar-4x3", no: "06/09" }, b: { ratio: "ar-4x3", no: "07/09" } },
      { kind: "right", ratio: "ar-4x5",  caption: "Plate VIII — The youngest",            no: "08/09" },
      { kind: "full",  ratio: "ar-4x3",  caption: "Plate IX — Us, together",              no: "09/09" },
    ],
  },
  {
    id: "weight-of-water",
    num: "No. 04",
    title: "The Weight of Water",
    titleKo: "물의 무게",
    year: "2021",
    count: 9,
    medium: "Archival pigment print",
    dims: "60 × 90 cm",
    edition: "Edition of 7 + 2 AP",
    tags: ["Landscape", "Water", "Long exposure"],
    lede: "서해 갯벌과 제주의 용천수를 십사 개월에 걸쳐 찾아다닌 기록.",
    essay: [
      "물은 담기기 전까지 자신의 모양을 알지 못한다. 나는 그 사실을 촬영하러 다녔다.",
    ],
    plates: [
      { kind: "wide",  ratio: "ar-21x9", caption: "Plate I — Low tide, 04:12 AM",        no: "01/09" },
      { kind: "pair",  a: { ratio: "ar-4x5", no: "02/09" }, b: { ratio: "ar-4x5", no: "03/09" } },
      { kind: "full",  ratio: "ar-3x4",  caption: "Plate IV — Spring water, basalt bed", no: "04/09" },
      { kind: "left",  ratio: "ar-4x3",  caption: "Plate V — Tidal flat, dusk",          no: "05/09" },
      { kind: "pair",  a: { ratio: "ar-4x3", no: "06/09" }, b: { ratio: "ar-4x5", no: "07/09" } },
      { kind: "right", ratio: "ar-4x5",  caption: "Plate VIII — Rain on still water",    no: "08/09" },
      { kind: "full",  ratio: "ar-4x3",  caption: "Plate IX — The sea at low light",     no: "09/09" },
    ],
  },
  {
    id: "after-rain",
    num: "No. 05",
    title: "After Rain",
    titleKo: "비 뒤에",
    year: "2025",
    count: 9,
    medium: "Large format film",
    dims: "100 × 125 cm",
    edition: "Edition of 5 + 2 AP",
    tags: ["Landscape", "Atmosphere", "Film"],
    lede: "비가 그치고 세상이 다시 시작되는 첫 몇 분을 포착하려는 시도. 냄새가 있는 사진.",
    essay: [
      "비가 오고 나면 세계는 잠깐 낯선 얼굴을 드러낸다. 아스팔트 위에 남겨진 물웅덩이, 젖은 잎사귀가 빛을 받아 새로 태어나는 순간. 이 연작은 그 전환의 찰나를 대형 포맷 필름에 담으려는 시도다.",
      "촬영 조건은 비가 그친 직후 30분 이내. 빛이 젖은 표면에서 반사되는 방식은 건조한 날과 근본적으로 다르다. 세계는 더 깊고, 더 조용하며, 잠시 더 솔직해진다.",
      "서울 도심부터 제주 한라산 중턱까지, 2024년 우기 전반에 걸쳐 촬영되었다.",
    ],
    plates: [
      { kind: "wide",  ratio: "ar-21x9", caption: "Plate I — Hannam-dong, 6:14 AM",      no: "01/09" },
      { kind: "pair",  a: { ratio: "ar-4x5", no: "02/09" }, b: { ratio: "ar-4x5", no: "03/09" } },
      { kind: "full",  ratio: "ar-4x5",  caption: "Plate IV — Wet pavement, Euljiro",    no: "04/09" },
      { kind: "left",  ratio: "ar-4x3",  caption: "Plate V — Hallasan slope, mist",      no: "05/09" },
      { kind: "pair",  a: { ratio: "ar-4x3", no: "06/09" }, b: { ratio: "ar-4x5", no: "07/09" } },
      { kind: "right", ratio: "ar-4x5",  caption: "Plate VIII — Rooftop puddle, noon",   no: "08/09" },
      { kind: "full",  ratio: "ar-4x3",  caption: "Plate IX — After the last rain",      no: "09/09" },
    ],
  },
];

// gallery: flattened set of works for the gallery grid
const WORKS = [
  { id:"w01", seriesId:"quiet-rooms",    title:"Closed Curtain",      no:"01/09", year:"2024", tags:["Interior"],   span:"c-6",  ratio:"ar-4x5" },
  { id:"w02", seriesId:"quiet-rooms",    title:"Chair by Window",     no:"03/09", year:"2024", tags:["Interior"],   span:"c-6",  ratio:"ar-4x5" },
  { id:"w03", seriesId:"salt-and-paper", title:"Crystal I",           no:"02/09", year:"2023", tags:["Still life"], span:"c-4",  ratio:"ar-4x5" },
  { id:"w04", seriesId:"salt-and-paper", title:"Folded Seven Times",  no:"04/09", year:"2023", tags:["Still life"], span:"c-4",  ratio:"ar-1x1" },
  { id:"w05", seriesId:"salt-and-paper", title:"Evaporation",         no:"05/09", year:"2023", tags:["Still life"], span:"c-4",  ratio:"ar-4x5" },
  { id:"w06", seriesId:"mother-tongue",  title:"Grandmother",         no:"01/09", year:"2022", tags:["Portrait"],   span:"c-8",  ratio:"ar-4x3" },
  { id:"w07", seriesId:"mother-tongue",  title:"Four Hands",          no:"04/09", year:"2022", tags:["Portrait"],   span:"c-4",  ratio:"ar-2x3" },
  { id:"w08", seriesId:"weight-of-water",title:"Low Tide",            no:"01/09", year:"2021", tags:["Landscape"],  span:"c-12", ratio:"ar-21x9" },
  { id:"w09", seriesId:"weight-of-water",title:"Basalt Bed",          no:"04/09", year:"2021", tags:["Landscape"],  span:"c-5",  ratio:"ar-3x4" },
  { id:"w10", seriesId:"quiet-rooms",    title:"Bedroom, Inherited",  no:"06/09", year:"2024", tags:["Interior"],   span:"c-7",  ratio:"ar-4x3" },
  { id:"w11", seriesId:"mother-tongue",  title:"Mother, Waiting",     no:"05/09", year:"2022", tags:["Portrait"],   span:"c-6",  ratio:"ar-4x5" },
  { id:"w12", seriesId:"salt-and-paper", title:"Cotton Blooming",     no:"07/09", year:"2023", tags:["Still life"], span:"c-6",  ratio:"ar-4x3" },
  { id:"w13", seriesId:"after-rain",     title:"Hannam-dong, 6:14 AM",no:"01/09", year:"2025", tags:["Landscape"],  span:"c-12", ratio:"ar-21x9" },
  { id:"w14", seriesId:"after-rain",     title:"Wet Pavement",        no:"04/09", year:"2025", tags:["Landscape"],  span:"c-5",  ratio:"ar-4x5" },
  { id:"w15", seriesId:"after-rain",     title:"Hallasan Mist",       no:"05/09", year:"2025", tags:["Landscape"],  span:"c-7",  ratio:"ar-4x3" },
  { id:"w16", seriesId:"after-rain",     title:"Rooftop Puddle",      no:"08/09", year:"2025", tags:["Landscape"],  span:"c-6",  ratio:"ar-4x5" },
  { id:"w17", seriesId:"weight-of-water",title:"Rain on Still Water", no:"08/09", year:"2021", tags:["Landscape"],  span:"c-6",  ratio:"ar-4x5" },
  { id:"w18", seriesId:"quiet-rooms",    title:"Window at Dusk",      no:"09/09", year:"2024", tags:["Interior"],   span:"c-6",  ratio:"ar-4x5" },
  { id:"w19", seriesId:"mother-tongue",  title:"The Youngest",        no:"08/09", year:"2022", tags:["Portrait"],   span:"c-6",  ratio:"ar-4x5" },
  { id:"w20", seriesId:"after-rain",     title:"After the Last Rain", no:"09/09", year:"2025", tags:["Landscape"],  span:"c-4",  ratio:"ar-4x3" },
];

const CV = {
  exhibitions: [
    { yr: "2025", ev: "Quiet Rooms — solo", where: "Gallery Hyundai, Seoul" },
    { yr: "2024", ev: "Material Language", where: "Aperture, New York" },
    { yr: "2023", ev: "Salt and Paper — solo", where: "PKM Gallery, Seoul" },
    { yr: "2022", ev: "The Soft Archive", where: "Foam, Amsterdam" },
    { yr: "2021", ev: "Seoul Photo Triennale", where: "SeMA, Seoul" },
    { yr: "2019", ev: "Mother Tongue — solo", where: "ONE AND J., Seoul" },
  ],
  publications: [
    { yr: "2024", ev: "Quiet Rooms", where: "IANN Books" },
    { yr: "2023", ev: "Aperture #253", where: "Guest portfolio" },
    { yr: "2022", ev: "Mother Tongue", where: "MACK Books" },
    { yr: "2020", ev: "British Journal of Photography", where: "Ones to Watch" },
  ],
  awards: [
    { yr: "2024", ev: "Prix Pictet — shortlist", where: "Geneva" },
    { yr: "2023", ev: "KT&G SKOPF Award", where: "Artist of the Year" },
    { yr: "2022", ev: "Hasselblad Masters", where: "Finalist, Fine Art" },
    { yr: "2019", ev: "Ilwoo Photo Prize", where: "Winner" },
  ],
};

Object.assign(window, { SITE, SERIES, WORKS, CV });
